services:
  web:
    env_file:
      - .django.env
      - .influxdb.env
      - .celery.env
    build: django/hlink
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             (celery -A hlink worker --loglevel=info &
             celery -A hlink beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler &
             python manage.py runserver 0.0.0.0:8000)"
    volumes:
      - ./django/hlink:/home/app/web
      - ./django/dev/db:/home/app/db/
      - ./django/dev/mediafiles:/home/app/static/mediafiles
      - ./django/dev/emails:/home/app/emails
    ports:
      - 8000:8000

  redis:
    image: redis:7-alpine

  flower:
    env_file:
      - .celery.env
    environment:
      TZ: Europe/Rome
    image: mher/flower
    container_name: flower
    command: celery flower
    ports:
      - 5555:5555
