services:
  web:
    build: django/hlink
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./django/hlink:/home/app/web
      - ./django/dev/db:/home/app/db/
      - ./django/dev/mediafiles:/home/app/static/mediafiles
      - ./django/dev/emails:/home/app/emails
    ports:
      - 8000:8000
    env_file:
      - ./.django.env
