# Generated by Django 5.1.6 on 2025-02-19 10:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('deliver_time', models.DateTimeField(blank=True, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(choices=[('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4'), ('H5', 'H5'), ('H6', 'H6')], max_length=2)),
                ('acq0', models.BinaryField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)])),
                ('acq', models.BinaryField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)])),
                ('asic0', models.BinaryField(blank=True, max_length=124, null=True, validators=[django.core.validators.MinLengthValidator(124)])),
                ('asic1', models.BinaryField(blank=True, max_length=124, null=True, validators=[django.core.validators.MinLengthValidator(124)])),
                ('bee', models.BinaryField(blank=True, max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(64)])),
                ('liktrg', models.BinaryField(blank=True, max_length=38, null=True, validators=[django.core.validators.MinLengthValidator(38)])),
                ('obs', models.BinaryField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
