# Generated by Django 5.1.6 on 2025-02-13 15:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('deliver_time', models.DateTimeField(blank=True, null=True)),
                ('uploaded', models.BooleanField(default=False)),
                ('upload_time', models.DateTimeField(blank=True, null=True)),
                ('model', models.CharField(choices=[('1', 'H1'), ('2', 'H2'), ('3', 'H3'), ('4', 'H4'), ('5', 'H5'), ('6', 'H6')], max_length=1)),
                ('acq', models.BinaryField(max_length=20, validators=[django.core.validators.MinLengthValidator(20)])),
                ('acq0', models.BinaryField(max_length=20, validators=[django.core.validators.MinLengthValidator(20)])),
                ('asic0', models.BinaryField(max_length=124, validators=[django.core.validators.MinLengthValidator(124)])),
                ('asic1', models.BinaryField(max_length=124, validators=[django.core.validators.MinLengthValidator(124)])),
                ('bee', models.BinaryField(max_length=64, validators=[django.core.validators.MinLengthValidator(64)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='configurations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
