# Generated by Django 5.1.6 on 2025-02-18 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='liktrg',
            field=models.BinaryField(blank=True, max_length=38, null=True, validators=[django.core.validators.MinLengthValidator(38)]),
        ),
        migrations.AddField(
            model_name='configuration',
            name='obs',
            field=models.BinaryField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='acq',
            field=models.BinaryField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='acq0',
            field=models.BinaryField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='asic0',
            field=models.BinaryField(blank=True, max_length=124, null=True, validators=[django.core.validators.MinLengthValidator(124)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='asic1',
            field=models.BinaryField(blank=True, max_length=124, null=True, validators=[django.core.validators.MinLengthValidator(124)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='bee',
            field=models.BinaryField(blank=True, max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(64)]),
        ),
    ]
