# Generated by Django 5.1.6 on 2025-03-01 21:14

import configs.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('submitted', models.BooleanField(default=False)),
                ('submit_time', models.DateTimeField(blank=True, null=True, validators=[configs.models.validate_not_future])),
                ('uplinked', models.BooleanField(default=False)),
                ('uplink_time', models.DateTimeField(blank=True, null=True, validators=[configs.models.validate_not_future])),
                ('model', models.CharField(choices=[('H1', 'H1'), ('H2', 'H2'), ('H3', 'H3'), ('H4', 'H4'), ('H5', 'H5'), ('H6', 'H6')], max_length=2)),
                ('acq0', models.BinaryField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)])),
                ('acq', models.BinaryField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(20)])),
                ('asic0', models.BinaryField(blank=True, max_length=124, null=True, validators=[django.core.validators.MinLengthValidator(124)])),
                ('asic1', models.BinaryField(blank=True, max_length=124, null=True, validators=[django.core.validators.MinLengthValidator(124)])),
                ('bee', models.BinaryField(blank=True, max_length=64, null=True, validators=[django.core.validators.MinLengthValidator(64)])),
                ('liktrg', models.BinaryField(blank=True, max_length=38, null=True, validators=[django.core.validators.MinLengthValidator(38)])),
                ('obs', models.BinaryField(blank=True, max_length=5, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_configurations', to=settings.AUTH_USER_MODEL)),
                ('uplinked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='uplinked_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('acq__isnull', False), ('acq0__isnull', False), ('asic0__isnull', False), ('asic1__isnull', False), ('bee__isnull', False), ('liktrg__isnull', False), ('obs__isnull', False), _connector='OR'), name='at_least_one_config_field'), models.CheckConstraint(condition=models.Q(('submit_time__isnull', True), ('uplink_time__isnull', True), ('uplink_time__gt', models.F('submit_time')), _connector='OR'), name='uplink_after_submit'), models.CheckConstraint(condition=models.Q(('submit_time__isnull', True), ('submitted', True), _connector='OR'), name='submit_time_requires_submitted'), models.CheckConstraint(condition=models.Q(('uplink_time__isnull', True), ('uplinked', True), _connector='OR'), name='uplink_time_requires_uplinked'), models.CheckConstraint(condition=models.Q(('submitted', True), ('uplinked', False), _connector='OR'), name='uplinked_requires_submitted'), models.CheckConstraint(condition=models.Q(models.Q(('uplinked', False), ('uplinked_by__isnull', True)), models.Q(('uplinked', True), ('uplinked_by__isnull', False)), _connector='OR'), name='uplinked_iff_uplinked_by')],
            },
        ),
    ]
