"""
Django settings for hlink project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(int(os.environ.get("DEBUG", default="0")))
# p. catches test environments preventing the debug toolbar to mess with it
TESTING = "test" in sys.argv

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", default="").split(" ")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # p. custom apps
    "django_celery_beat",
    "main",
    "accounts",
    "configs",
    "logger",
]

# p. we do not install the debug toolbar when testing or running in production
if DEBUG and not TESTING:
    INSTALLED_APPS += [
        "debug_toolbar",
    ]

    DEBUG_TOOLBAR_CONFIG = {
        # p. since we are not installing the toobard in prod or debug it's no
        #    problem to have it up all the time.
        "SHOW_TOOLBAR_CALLBACK": lambda _: True,
    }

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # p. custom middleware
    "hlink.middleware.rate_limiter",
]


# p. we do not install the debug toolbar when testing or running in production
if DEBUG and not TESTING:
    MIDDLEWARE += [
        "debug_toolbar.middleware.DebugToolbarMiddleware",
    ]

ROOT_URLCONF = "hlink.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.service_status",
            ],
        },
    },
]

WSGI_APPLICATION = "hlink.wsgi.application"

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {
            "min_length": 12,
        },
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Rome"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.environ.get("DB_HOST"),
        "NAME": os.environ.get("POSTGRES_DB"),
        "USER": os.environ.get("POSTGRES_USER"),
        "PASSWORD": os.environ.get("POSTGRES_PASSWORD"),
    },
}

# p. logging
ADMINS = [
    ("Peppe", "peppedilillo@gmail.com"),
]

# p. The environment variable `LOG_DIR` is defined in dockerfile.
LOG_DIR = Path(os.environ.get("LOG_DIR"))

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "null": {
            "class": "logging.NullHandler",
        },
        "cache": {
            "class": "logger.handlers.CacheHandler",
        },
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
        "file": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": LOG_DIR / "hlink.log",
            "when": "midnight",
            "backupCount": 30,
            "formatter": "standard",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "include_html": True,
        },
    },
    "formatters": {
        "standard": {"format": "%(asctime)s [%(levelname)s] %(name)s: %(message)s"},
    },
    "loggers": {
        "hlink": {
            "handlers": ["cache"] if not TESTING else ["null"],
            "level": "DEBUG",
            "propagate": True,
        },
        "": {
            "handlers": ["console", "file", "mail_admins"] if not TESTING else ["null"],
            "level": "INFO",
        },
    },
}

# p. Caches
CACHE_HOST = os.environ.get("CACHE_HOST")
CACHE_PORT = os.environ.get("CACHE_PORT")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": f"redis://{CACHE_HOST}:{CACHE_PORT}/0",
    }
}

# p: custom user model
AUTH_USER_MODEL = "accounts.CustomUser"

# p. The environment variable `STATIC_DIR` is defined in dockerfile.
STATIC_ROOT = Path(os.environ.get("STATIC_DIR"))

MEDIA_URL = "/media/"
# p. The environment variable `MEDIA_DIR` is defined in dockerfile.
MEDIA_ROOT = Path(os.environ.get("MEDIA_DIR"))

# p. sets entrusted csrf urls
CSRF_TRUSTED_ORIGINS = [
    "https://hermeslink.ssdc.asi.it",
    "http://localhost:80",
    "http://localhost:443",
]

# p. https settings
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# p. sets login url to index instead of profile page
LOGIN_REDIRECT_URL = "/"

# p. email settings
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
    # p. the `EMAIL_DIR` environment variable should be set by docker file
    EMAIL_FILE_PATH = Path(os.environ.get("EMAIL_DIR"))
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_HOST = os.environ.get("EMAIL_HOST")
    EMAIL_PORT = os.environ.get("EMAIL_PORT")
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
    EMAIL_USE_TLS = bool(int(os.environ.get("EMAIL_USE_TLS", default=1)))
    EMAIL_USE_SSL = bool(int(os.environ.get("EMAIL_USE_SSL", default=0)))

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# p. celery settings
CELERY_BROKER_URL = f"redis://{CACHE_HOST}:{CACHE_PORT}/1"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

# p. influx db auth
INFLUXDB_URL = os.environ.get("INFLUXDB_URL", "http://influxdb2:8086")
INFLUXDB_TOKEN = os.environ.get("DOCKER_INFLUXDB_INIT_ADMIN_TOKEN")
INFLUXDB_ORG = os.environ.get("DOCKER_INFLUXDB_INIT_ORG")
INFLUXDB_BUCKET = os.environ.get("DOCKER_INFLUXDB_INIT_BUCKET")
